### ISSUE TITLE
Could not find a version of package nunomaduro/laravel-code-analyse matching your minimum-stability 

### ISSUE THREAD

**Issue by redrain-wang** [nunomaduro/laravel-code-analyse#6]
Could not find a version of package nunomaduro/laravel-code-analyse matching your minimum-stability (stable). Require it with an explicit version constraint allowing its desired stability.

**Comment by JulianMar** [comment]
I have the same Issue but after adding laravel-code-analyse to my composer.json I get this Error.

```
Problem 1
    - The requested package nunomaduro/laravel-code-analyse * is satisfiable by nunomaduro/laravel-code-analyse[dev-master] but these conflict with your requirements or minimum-stability.
```

**Comment by DaanGeurts** [comment]
It's because your composer project has a minimum-stability much higher than dev, probably stable and this package is still a dev release.
[Check the Composer documentation for more information](https://getcomposer.org/doc/04-schema.md#minimum-stability).

**Comment by nunomaduro** [comment]
@redrain-wang @JulianMar This package is under development and you shouldn't be using it.

Please follow me on [twitter](https://twitter.com/enunomaduro) or watch this repository. The beta release will be out real soon.
